### ISSUE TITLE
[Bug]: mattermost-desktop-5.9.0-win-arm64.msi installer declares itself as x64 architecture

### ISSUE THREAD

**Issue by mivsvit** [mattermost/desktop#3138]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.9.0

### Operating System

Windows 11

### Steps to reproduce

```
winget install komac
wget https://releases.mattermost.com/desktop/5.9.0/mattermost-desktop-5.9.0-win-arm64.msi
komac analyse mattermost-desktop-5.9.0-win-arm64.msi
```
Note `Architecture: x64` rather than `Architecture: amd64` in the output. 

### Expected behavior

`Architecture: amd64` not `x64`.

### Observed behavior

```
komac analyse mattermost-desktop-5.9.0-win-arm64.msi
InstallerLocale: en-US
Architecture: x64
InstallerType: wix
InstallerUrl: https://www.example.com/
InstallerSha256: 2A13566E780CCAED7A944C974AE547E7B045D2A4D25602740D210AECE3F028C8
ProductCode: '{91E31A20-A266-45F0-A400-7A099F456ADE}'
AppsAndFeaturesEntries:
- DisplayName: Mattermost
  Publisher: Mattermost, Inc.
  DisplayVersion: 5.9.0.0
  ProductCode: '{91E31A20-A266-45F0-A400-7A099F456ADE}'
  UpgradeCode: '{0F183CAA-DF79-5400-A71F-684F563AF31C}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\mattermost-desktop'
  ```

### Log Output

```shell
n/a
```

### Additional Information

![363442455-3e46e130-ca95-48d0-b890-b57c49ac4efc](https://github.com/user-attachments/assets/93cdd243-43ec-439a-a0d8-082bcf136a04)
